### ISSUE TITLE
Running locally refreshes constantly

### ISSUE THREAD

**Issue by collinlucke** [sebsebmc/helldivers-history#1]
See this awesome gif...

![2024-04-06 18-03-46](https://github.com/sebsebmc/helldivers-history/assets/6249375/b2d35433-6338-4c5a-a54b-c2c64d4c75ef)

Here's a chuck of what the terminal spit out. This just kept repeating...

`GET /
GET /_observablehq/theme-near-midnight,alt,wide.css
GET /_npm/d3-brush@3.0.0/_esm.js
GET /_npm/d3-ease@3.0.1/_esm.js
GET /_npm/d3-drag@3.0.0/_esm.js
GET /_npm/d3-dsv@3.0.1/_esm.js
GET /_npm/d3-fetch@3.0.1/_esm.js
GET /_observablehq/stdlib/inputs.css
GET /_npm/d3-force@3.0.0/_esm.js
GET /_npm/d3-format@3.1.0/_esm.js
GET /_npm/d3-path@3.1.0/_esm.js
GET /_npm/d3-interpolate@3.0.1/_esm.js
GET /_npm/d3-geo@3.1.1/_esm.js
GET /_npm/d3-hierarchy@3.1.2/_esm.js
GET /_npm/d3-polygon@3.0.1/_esm.js
GET /_npm/d3-scale-chromatic@3.1.0/_esm.js
GET /_npm/d3-quadtree@3.0.1/_esm.js
GET /_npm/d3-random@3.0.1/_esm.js
GET /_npm/d3-scale@4.0.2/_esm.js
GET /_npm/d3-selection@3.0.0/_esm.js
GET /_npm/d3-shape@3.2.0/_esm.js
GET /_npm/d3-time@3.1.0/_esm.js
GET /_npm/d3-time-format@4.1.0/_esm.js
GET /_npm/d3-zoom@3.0.0/_esm.js
GET /_npm/d3-timer@3.0.1/_esm.js
GET /_npm/d3-transition@3.0.1/_esm.js
GET /_npm/binary-search-bounds@2.0.5/_esm.js
GET /_npm/internmap@2.0.3/_esm.js
GET /_npm/delaunator@5.0.1/_esm.js
GET /_npm/robust-predicates@3.0.2/_esm.js
GET /_observablehq/client.js
GET /_observablehq/runtime.js
GET /_observablehq/stdlib.js
GET /_observablehq/stdlib/inputs.js
GET /_import/components/planet_history.js?sha=eff04bd408f4edd623bd7b7840668c347ff7056bbfd45be58642a4d4c870214f
GET /_npm/@observablehq/plot@0.6.14/_esm.js
GET /_npm/d3@7.9.0/_esm.js
GET /_npm/htl@0.3.1/_esm.js
GET /_npm/interval-tree-1d@1.0.4/_esm.js
GET /_npm/isoformat@0.2.1/_esm.js
GET /_npm/d3-array@3.2.4/_esm.js
GET /_npm/d3-axis@3.0.0/_esm.js
GET /_npm/d3-chord@3.0.1/_esm.js
GET /_npm/d3-color@3.1.0/_esm.js
GET /_npm/d3-contour@4.0.2/_esm.js
GET /_npm/d3-delaunay@6.0.4/_esm.js
GET /_npm/d3-dispatch@3.0.1/_esm.js
GET /_file/data/sector_map.svg?sha=562371b96ba09bef94f02496df97101de1cc096e227c4c995ae550a5046f3235
socket open /_observablehq
↑ {
  type: 'hello',
  path: '/',
  hash: '172462eacc183ecbfbc796f3167cb1dd0be386cc1e9d14f595373939bc6e969e'
}
GET /_file/data/helldivers.json?sha=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
GET /_file/data/aggregates.json?sha=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
GET /_file/data/recent_attacks.json?sha=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
GET /
socket close /_observablehq
GET /_observablehq/client.js
GET /_observablehq/runtime.js
GET /_observablehq/stdlib.js
GET /_import/components/planet_history.js?sha=eff04bd408f4edd623bd7b7840668c347ff7056bbfd45be58642a4d4c870214f
GET /_npm/@observablehq/plot@0.6.14/_esm.js
GET /_npm/d3@7.9.0/_esm.js
GET /_npm/htl@0.3.1/_esm.js
GET /_observablehq/stdlib/inputs.js
GET /_npm/isoformat@0.2.1/_esm.js
GET /_npm/interval-tree-1d@1.0.4/_esm.js
GET /_npm/d3-array@3.2.4/_esm.js
GET /_npm/d3-axis@3.0.0/_esm.js
GET /_npm/d3-chord@3.0.1/_esm.js
GET /_npm/d3-brush@3.0.0/_esm.js
GET /_npm/d3-color@3.1.0/_esm.js
GET /_npm/d3-contour@4.0.2/_esm.js
GET /_npm/d3-delaunay@6.0.4/_esm.js
GET /_npm/d3-dispatch@3.0.1/_esm.js
GET /_npm/d3-dsv@3.0.1/_esm.js
GET /_npm/d3-drag@3.0.0/_esm.js
GET /_npm/d3-ease@3.0.1/_esm.js
GET /_npm/d3-force@3.0.0/_esm.js
GET /_npm/d3-fetch@3.0.1/_esm.js
GET /_npm/d3-format@3.1.0/_esm.js
GET /_npm/d3-geo@3.1.1/_esm.js
GET /_npm/d3-hierarchy@3.1.2/_esm.js
GET /_npm/d3-interpolate@3.0.1/_esm.js
GET /_npm/d3-path@3.1.0/_esm.js
GET /_npm/d3-polygon@3.0.1/_esm.js
GET /_npm/d3-quadtree@3.0.1/_esm.js
GET /_npm/d3-random@3.0.1/_esm.js
GET /_npm/d3-scale-chromatic@3.1.0/_esm.js
GET /_npm/d3-scale@4.0.2/_esm.js
GET /_npm/d3-selection@3.0.0/_esm.js
GET /_npm/d3-shape@3.2.0/_esm.js
GET /_npm/d3-time-format@4.1.0/_esm.js
GET /_npm/d3-timer@3.0.1/_esm.js
GET /_npm/d3-time@3.1.0/_esm.js
GET /_npm/d3-zoom@3.0.0/_esm.js
GET /_npm/d3-transition@3.0.1/_esm.js
GET /_npm/binary-search-bounds@2.0.5/_esm.js
GET /_npm/internmap@2.0.3/_esm.js
GET /_npm/delaunator@5.0.1/_esm.js
GET /_npm/robust-predicates@3.0.2/_esm.js
GET /_file/data/sector_map.svg?sha=562371b96ba09bef94f02496df97101de1cc096e227c4c995ae550a5046f3235
socket open /_observablehq
↑ {
  type: 'hello',
  path: '/',
  hash: '172462eacc183ecbfbc796f3167cb1dd0be386cc1e9d14f595373939bc6e969e'
}
GET /_file/data/helldivers.json?sha=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
GET /_file/data/aggregates.json?sha=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
GET /_file/data/recent_attacks.json?sha=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
GET /
socket close /_observablehq
GET /_observablehq/client.js
GET /_observablehq/runtime.js
GET /_observablehq/stdlib.js
GET /_import/components/planet_history.js?sha=eff04bd408f4edd623bd7b7840668c347ff7056bbfd45be58642a4d4c870214f
GET /_npm/@observablehq/plot@0.6.14/_esm.js
GET /_npm/d3@7.9.0/_esm.js
GET /_npm/htl@0.3.1/_esm.js
GET /_observablehq/stdlib/inputs.js
GET /_npm/isoformat@0.2.1/_esm.js
GET /_npm/interval-tree-1d@1.0.4/_esm.js
GET /_npm/d3-array@3.2.4/_esm.js
GET /_npm/d3-axis@3.0.0/_esm.js`

Looks like you made some awesome shit.... I just want to see it :-D

**Comment by sebsebmc** [comment]
Are you running this with `npm run dev` or are you building it and viewing it locally? 

Because of how the page is deployed I added a condition that if it fails to read helldivers.json it reloads the page. You can try running `npm run update` which will pull all the new data in the repo and run build_stats.py which will generate the aggregates files and move a copy of helldivers.json to where it's expected to be
