### ISSUE TITLE
Incorrect grouping of sectors (and other issues of position and such details

### ISSUE THREAD

**Issue by Cometstreak** [sebsebmc/helldivers-history#2]
When it comes to grouping of sectors, they are grouped improperly, namely hellmire not being in the Cancri sector. In addition, I think that the positioning of all the planets are wrong.

**Comment by Cometstreak** [comment]
This relates to the Json labeled "Helldivers,json"

**Comment by sebsebmc** [comment]
The visual positioning of the sectors is definitely a bit off and thats mostly a result of me using an SVG as a background image and then plotting the planets on top. However, `helldivers.json` is not something that I control, that data is actually pulled from the API the game uses. Do you have a planet position value that you can provide that you believe is wrong and what the correct value should be?

**Comment by sebsebmc** [comment]
Hellmire in the game is in Mirin sector

**Comment by Titanic880** [comment]
> When it comes to grouping of sectors, they are grouped improperly, namely hellmire not being in the Cancri sector. In addition, I think that the positioning of all the planets are wrong.

Would it be possible for you to provide screenshots of this? I am not able to replicate it.
